export const GET_GROUP_ADMIN_PRODUCTION_START = 'GET_GROUP_ADMIN_PRODUCTION_START';
export const GET_GROUP_ADMIN_PRODUCTION_ERROR = 'GET_GROUP_ADMIN_PRODUCTION_ERROR';
export const GET_GROUP_ADMIN_PRODUCTION_SUCCESS = 'GET_GROUP_ADMIN_PRODUCTION_SUCCESS';

export const REMOVE_GROUP_ADMIN_PRODUCTION_START = 'REMOVE_GROUP_ADMIN_PRODUCTION_START';
export const REMOVE_GROUP_ADMIN_PRODUCTION_ERROR = 'REMOVE_GROUP_ADMIN_PRODUCTION_ERROR';
export const REMOVE_GROUP_ADMIN_PRODUCTION_SUCCESS = 'REMOVE_GROUP_ADMIN_PRODUCTION_SUCCESS';