// get group info
export const GET_MEMBER_PRODUCTION_TAB_START = 'GET_MEMBER_PRODUCTION_TAB_START';
export const GET_MEMBER_PRODUCTION_TAB_ERROR = 'GET_MEMBER_PRODUCTION_TAB_ERROR';
export const GET_MEMBER_PRODUCTION_TAB_SUCCESS = 'GET_MEMBER_PRODUCTION_TAB_SUCCESS';