// get group info
export const CREATE_GROUP_MEMBER_START = 'CREATE_GROUP_MEMBER_START';
export const CREATE_GROUP_MEMBER_ERROR = 'CREATE_GROUP_MEMBER_ERROR';
export const CREATE_GROUP_MEMBER_SUCCESS = 'CREATE_GROUP_MEMBER_SUCCESS';