// GROUPS
export const GET_PRODUCTION_GROUPS_START = 'GET_PRODUCTION_GROUPS_START';
export const GET_PRODUCTION_GROUPS_SUCCESS = 'GET_PRODUCTION_GROUPS_SUCCESS';
export const GET_PRODUCTION_GROUPS_ERROR = 'GET_PRODUCTION_GROUPS_ERROR';
export const DELETE_PRODUCTION_GROUP_SUCCESS= 'DELETE_PRODUCTION_GROUP_SUCCESS'