// get group info
export const GET_GROUP_INFO_PRODUCTION_START = 'GET_GROUP_INFO_PRODUCTION_START';
export const GET_GROUP_INFO_PRODUCTION_ERROR = 'GET_GROUP_INFO_PRODUCTION_ERROR';
export const GET_GROUP_INFO_PRODUCTION_SUCCESS = 'GET_GROUP_INFO_PRODUCTION_SUCCESS';