export const GET_FINES_PRODUCTION_TAB_START = 'GET_FINES_PRODUCTION_TAB_START';
export const GET_FINES_PRODUCTION_TAB_ERROR = 'GET_FINES_PRODUCTION_TAB_ERROR';
export const GET_FINES_PRODUCTION_TAB_SUCCESS = 'GET_FINES_PRODUCTION_TAB_SUCCESS';