export const GET_LOAN_ACCOUNTS_START = 'GET_LOAN_ACCOUNTS_START';
export const GET_LOAN_ACCOUNTS_SUCCESS = 'GET_LOAN_ACCOUNTS_SUCCESS';
export const GET_LOAN_ACCOUNTS_ERROR = 'GET_LOAN_ACCOUNTS_ERROR';

export const SET_ACTIVE_LOAN_ACCOUNT_START = 'SET_ACTIVE_LOAN_ACCOUNT_START';
export const SET_ACTIVE_LOAN_ACCOUNT_SUCCESS = 'SET_ACTIVE_LOAN_ACCOUNT_SUCCESS';
export const SET_ACTIVE_LOAN_ACCOUNT_ERROR = 'GET_ACTIVE_LOAN_ACCOUNTS_ERROR';

export const CLEAR_ACTIVE_LOAN_ACCOUNT_START = 'CLEAR_ACTIVE_ACCOUNT_START';