export const GET_MEMBER_BILLPAYMENTS_START = 'GET_MEMBER_BILLPAYMENTS_START';
export const GET_MEMBER_BILLPAYMENTS_SUCCESS = 'GET_MEMBER_BILLPAYMENTS_SUCCESS';
export const GET_MEMBER_BILLPAYMENTS_ERROR = 'GET_MEMBER_BILLPAYMENTS_ERROR';

// export const SET_ACTIVE_LOAN_ACCOUNT_START = 'SET_ACTIVE_LOAN_ACCOUNT_START';
// export const SET_ACTIVE_LOAN_ACCOUNT_SUCCESS = 'SET_ACTIVE_LOAN_ACCOUNT_SUCCESS';
// export const SET_ACTIVE_LOAN_ACCOUNT_ERROR = 'GET_ACTIVE_LOAN_ACCOUNTS_ERROR';

export const LOAD_BILLPAYMENTS_PSP_START = 'LOAD_BILLPAYMENTS_PSP_START';
export const LOAD_BILLPAYMENTS_PSP_SUCCESS = 'LOAD_BILLPAYMENTS_PSP_SUCCESS';
export const LOAD_BILLPAYMENTS_PSP_ERROR = 'LOAD_BILLPAYMENTS_PSP_ERROR';

// export const CLEAR_ACTIVE_LOAN_ACCOUNT_START = 'CLEAR_ACTIVE_ACCOUNT_START';
